### ISSUE TITLE
Add map visualization

### ISSUE THREAD

**Issue by BeritJanssen** [CentreForDigitalHumanities/I-analyzer#1408]
**Is your feature request related to a problem? Please describe.**
If a corpus has geographical metadata, we would like to visualize this on a map.

**Describe the solution you'd like**
Perhaps this [ChartJS plugin](https://www.npmjs.com/package/chartjs-chart-geo) is interesting

**Describe alternatives you've considered**
Other geo visualization libraries exist, e.g. maplibre (cf. [in this repo](https://github.com/UUDigitalHumanitieslab/jewish-settlement-inscriptions/blob/develop/src/index.js)

**Comment by lukavdplas** [comment]
Can we add more information to this issue?

Things like:
- What question is the map supposed to answer?
- Where should it be displayed?
- What geographical information should be visible, if any?

**Comment by lukavdplas** [comment]
Some thoughts:

- I already mentioned this in our last meeting, but for the record: if we intend to work on https://github.com/UUDigitalHumanitieslab/I-analyzer/discussions/1427 in the future and roughly follow the implementation suggested there (both are big ifs), it would be a good idea to build new visualisations with the following principles:
	- Use a visualisation library with _declarative_ syntax, such as Plotly or Vega. Both of those have some support for maps, but I'm not sure if they would meet our needs.
	- Try to implement functionality in the backend rather than the frontend. Centre the visualisation around a _backend_ endpoint that essentially takes the query and some additional parameters and returns the result - rather than using the _frontend_ to construct aggregation queries that the backend merely forwards to elasticsearch.
- For the frontend component, `Results` is a useful base class for fetching data based on a query, but it hasn't yet been implemented in other visualisations (https://github.com/UUDigitalHumanitieslab/I-analyzer/issues/1468 ).
- I added a "needs mockup" label to the issue because it's the kind of thing that could benefit from creating a picture before you get into the nitty gritty, but I'm not involved in this project, so it's up to you.

**Comment by ar-jan** [comment]
The initial map component has been merged into develop, the actual map visualization is to be implemented (probably requires Angular to be updated).

**Comment by ar-jan** [comment]
#1549 works with ngx-maplibre-gl, but it's worth checking if the features we need are supported by Vega or Plotly.

Vega-Lite (and therefore Vega-Altair which produces Vega-Lite) does not yet support zoomable maps.

If we do want to use maplibre, we need to add a different base layer (include local assets, or use a service?) and fix the tests.

**Comment by lukavdplas** [comment]
@ar-jan I think this is done, right?
